// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MongoDB.Bson.FSharp")>]
[<assembly: AssemblyProductAttribute("MongoDB.Bson.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("MongoDB Bson serializers for F# types")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MongoDB.Bson.FSharp"
    let [<Literal>] AssemblyProduct = "MongoDB.Bson.FSharp"
    let [<Literal>] AssemblyDescription = "MongoDB Bson serializers for F# types"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
