name: .NET Core

on:
  push:
    paths:
      - 'src/**'
    branches:
      - master
  pull_request:
    paths:
      - 'src/**'
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
      # Publish
    - name: publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/MongoDB.Bson.FSharp/MongoDB.Bson.FSharp.fsproj # Relative to repository root
        # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
        # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
        # TAG_COMMIT: true # Flag to enable / disalge git tagging
        # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
        NUGET_KEY: ${{secrets.NUGET_KEY}}
